{% set name = "extensisq" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/extensisq-{{ version }}.tar.gz
  sha256: e68b3d93775c456c200b9561c1ca3e8e300a1f70859619f6bd0e221ba44bff14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.4.0
    - python >=3.6
    - scipy >=1.0.0

test:
  imports:
    - extensisq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WRKampi/extensisq
  summary: Extend scipy.integrate with various methods for solve_ivp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WRKampi
