{% set name = "extensisq" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/extensisq-{{ version }}.tar.gz
  sha256: e93075a4637aaa12c09abfabeaf5b40870cc7f859cde7c7697610093ee064f7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.22.0
    - scipy >=1.8.0

test:
  imports:
    - extensisq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WRKampi/extensisq
  summary: Extend scipy.integrate with various methods for solve_ivp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WRKampi
